package me.giiena.pigeonchat.client.renderer.entity;

import me.giiena.pigeonchat.entity.Pigeon;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;
import org.jspecify.annotations.NonNull;

import java.util.Objects;

public class PigeonModel extends EntityModel<PigeonRenderState> {
	public final ModelPart head;
	public final ModelPart beak;
	public final ModelPart bow;
	public final ModelPart torso;
	public final ModelPart tail;
	public final ModelPart rWing;
	public final ModelPart lWing;
	public final ModelPart rLeg;
	public final ModelPart lLeg;

	public PigeonModel(ModelPart root) {
		super(root);
		this.head = root.getChild("head");
		this.beak = this.head.getChild("beak");
		this.bow = this.head.getChild("bow");
		this.torso = root.getChild("torso");
		this.tail = root.getChild("tail");
		this.rWing = root.getChild("rWing");
		this.lWing = root.getChild("lWing");
		this.rLeg = root.getChild("rLeg");
		this.lLeg = root.getChild("lLeg");
	}

	// Generated by Blockbench then adjusted by hand.
	// Always make changes in the Blockbench model first.
	//
	// Model blockbench/Pigeon.bbmodel
	public static LayerDefinition createBodyLayer() {
		MeshDefinition meshdefinition = new MeshDefinition();
		PartDefinition partdefinition = meshdefinition.getRoot();

		PartDefinition head = partdefinition.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -1.5F, -1.5F, 3.0F, 3.0F, 3.0F, new CubeDeformation(0.0F))
				.texOffs(13, 2).addBox(-1.5F, 1.5F, -1.5F, 3.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offset(-1.0F, 14.0F, -2.5F));
		head.addOrReplaceChild("beak", CubeListBuilder.create().texOffs(26, 4).addBox(-0.5F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.5F, -2.0F));
		head.addOrReplaceChild("bow", CubeListBuilder.create().texOffs(4, 26).addBox(0.0F, -1.0F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
				.texOffs(8, 24).addBox(-0.75F, -1.75F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
				.texOffs(0, 24).addBox(0.75F, -1.75F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
				.texOffs(0, 28).addBox(0.75F, -0.5F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F))
				.texOffs(8, 28).addBox(-0.75F, -0.5F, 0.0F, 1.0F, 1.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-0.5F, 0.25F, 1.75F));
		partdefinition.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(0, 7).addBox(-2.0F, -3.5F, -2.0F, 4.0F, 7.0F, 4.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 19.0199F, -1.2173F, 0.4363F, 0.0F, 0.0F));
		partdefinition.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(4, 19).addBox(-1.5F, -0.0858F, -0.5F, 3.0F, 3.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.0F, 20.3467F, 1.0745F, 0.7854F, 0.0F, 0.0F));
		partdefinition.addOrReplaceChild("rWing", CubeListBuilder.create().texOffs(17, 9).addBox(-1.0F, 0.0206F, -1.5293F, 1.0F, 6.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.0F, 15.8167F, -2.6786F, 0.4363F, 0.0F, 0.0F));
		partdefinition.addOrReplaceChild("lWing", CubeListBuilder.create().texOffs(17, 9).addBox(0.0F, 0.0206F, -1.5293F, 1.0F, 6.0F, 3.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.0F, 15.8167F, -2.6786F, 0.4363F, 0.0F, 0.0F));
		partdefinition.addOrReplaceChild("rLeg", CubeListBuilder.create().texOffs(17, 20).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(-2.0F, 22.0F, 0.0F));
		partdefinition.addOrReplaceChild("lLeg", CubeListBuilder.create().texOffs(17, 20).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 2.0F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 22.0F, 0.0F));

		return LayerDefinition.create(meshdefinition, 32, 32);
	}

	@Override
	public void setupAnim(@NonNull PigeonRenderState state) {
		super.setupAnim(state);
		this.prepare(state.pose);
		this.head.xRot = state.xRot * Mth.DEG_TO_RAD;
		this.head.yRot = state.yRot * Mth.DEG_TO_RAD;
		this.bow.visible = state.columbina;

		switch (state.pose) {
			case STANDING:
				this.lLeg.xRot += Mth.cos(state.walkAnimationPos * 0.6662f) * 1.4f *
						state.walkAnimationSpeed;
				this.rLeg.xRot += Mth.cos(state.walkAnimationPos * 0.6662f + (float) Math.PI) *
						1.4f * state.walkAnimationSpeed;
			case FLYING:
			default:
				float bobbingBody = state.flapAngle * 0.3f;
				this.tail.xRot += Mth.cos(state.walkAnimationPos * 0.6662f) * 0.3f *
						state.walkAnimationSpeed;
				this.lWing.zRot = 0.0873f - state.flapAngle;
				ModelPart lWing = this.lWing;
				lWing.y += bobbingBody;
				this.rWing.zRot = 0.0873f + state.flapAngle;
				ModelPart rWing = this.rWing;
				rWing.y += bobbingBody;
				break;
		}
	}

	private void prepare(Pose pose) {
		if (Objects.requireNonNull(pose) == Pose.FLYING) {
			ModelPart leg = this.lLeg;
			leg.xRot += 0.6981317f;
			leg = this.rLeg;
			leg.xRot += 0.6981317f;
			ModelPart tail = this.tail;
			tail.xRot += 10 * Mth.DEG_TO_RAD;
		}
	}

	public static Pose getPose(Pigeon entity) {
		return entity.isFlying() ? Pose.FLYING : Pose.STANDING;
	}

	public enum Pose {
		FLYING,
		STANDING
	}
}